config/routes.rb
Rails.application.routes.draw do
    # get "static_pages/index"  => "static_pages#index"
    root                           "static_pages#index"
    # get "wishes/new" => "wishes#new"
    resources :wishes
    resources :incomes
    resources :loans
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/income.rb
class Income < ApplicationRecord
    validates :name, presence: true
    validates :receipt, presence: true
end

app/models/loan.rb
class Loan < ApplicationRecord
    validates :name, presence: true
    validates :amount, presence: true
end

app/models/wish.rb
class Wish < ApplicationRecord
    validates :name, presence: true
    validates :price, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController

    def new
        @income = Income.new
    end

    def create
        @income = Income.new(income_params)
        if @income.save
            # flash[:success] = "収入を反映しました"
            redirect_to root_path(income_receipt: @income.receipt)
            flash[:success] = "収入を反映しました"
        else
            render 'new'
        end
    end

    def destroy
        Income.find(params[:id]).destroy
        flash[:success] = "収入データを削除しました"
        redirect_to root_url
    end

    private

        def income_params
            params.required(:income).permit(:name, :receipt)
        end

end

app/controllers/loans_controller.rb
class LoansController < ApplicationController

    def new
        @loan = Loan.new
    end

    def create
        @loan = Loan.new(loan_params)
        if @loan.save
            redirect_to root_path
        else
            render 'new'
        end
    end

    def destroy
        Loan.find(params[:id]).destroy
        flash[:success] = "リストを削除しました"
        redirect_to root_url
    end

    def update
        Loan.find(params[:id]).update_attribute(:repaid, true)
        flash[:success] = "返済されました!"
        redirect_to root_url
    end

    private

        def loan_params
            params.required(:loan).permit(:name, :amount)
        end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

    def index
       @wallet = Income.sum(:receipt) - Wish.where(purchased: true).sum(:price) + Loan.where(repaid: true).sum(:amount)
       @wishes = Wish.all
       @loans = Loan.all
    end


end

app/controllers/wishes_controller.rb
class WishesController < ApplicationController

    def new
        @wish = Wish.new
    end

    def create
        @wish = Wish.new(wish_params)
        if @wish.save
            redirect_to root_path
        else
            render 'new'
        end
    end

    def destroy
        Wish.find(params[:id]).destroy
        flash[:success] = "欲しいものリストから削除しました"
        redirect_to root_url
    end

    def update
        Wish.find(params[:id]).update_attribute(:purchased, true)
        flash[:success] = "欲しいものが買えました！"
        redirect_to root_url
    end 

    private

        def wish_params
            params.required(:wish).permit(:name, :price)
        end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/incomes_helper.rb
module IncomesHelper
end

app/helpers/loans_helper.rb
module LoansHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/wishes_helper.rb
module WishesHelper
end

app/views/incomes/new.html.erb
<h1>収入を追加する</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
  <%= form_for(@income) do |f| %>
    <%= f.label :なんの収入? %>
    <%= f.text_field :name %>

    <%= f.label :金額 %>
    <%= f.number_field :receipt %>

    <%= f.submit "決定", class: "btn btn-primary" %>
  <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShiftManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/loans/new.html.erb
<h1>貸与金を追加する</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
  <%= form_for(@loan) do |f| %>
    <%= f.label :誰に貸してる? %>
    <%= f.text_field :name %>

    <%= f.label :金額 %>
    <%= f.number_field :amount %>

    <%= f.submit "決定", class: "btn btn-primary" %>
  <% end %>
  </div>
</div>

app/views/static_pages/index.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>俺の小遣い帳</title>
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css">
    </head>

    <body>
    <h1>所持金<%= @wallet %>円</h1>

    <!--ここからコメントアウト
    行を追加します<input type="button" value="行を追加" id="coladd" onclick="coladd()">
        
    <table id="table" border="1">
        <tr>
            <td>
                商品
            </td>
            <td>
                値段
            </td>
        </tr>
    </table> 
    ここまで-->
    <h1>収入リスト<i class="fas fa-money-bill"></i></i></h1>
    <button><%= link_to "収入を追加する",'incomes/new'%></button>
    <h1>欲しいものリスト<i class="fas fa-meteor"></i></h1>
    <button><%= link_to "欲しいものを追加する", 'wishes/new' %></button>
    <div class="wishes">
        <% @wishes.each do |wish| %>
            <% if wish.purchased == false %>
            <li><%= wish.name %></li>
            <li><%= wish.price %></li>
            <li><%= link_to "買った!", wish_path(wish), method: :put %></li>
            <li><%= link_to "削除する", wish,  method: :delete,
                                        date: { confirm: "本当によろしいですか?"} %></li>
            <% end %>
        <% end %>
    </div>
    <h1>貸与金リスト<i class="fas fa-skull-crossbones"></i></h1>
    <button><%= link_to "貸与金リストを追加する", 'loans/new' %></button>
    <div class="loans">
        <% @loans.each do |loan| %>
            <% if loan.repaid == false %>
            <li><%= loan.name %></li>
            <li><%= loan.amount %></li>
            <li><%= link_to "返してもらった!", loan_path(loan), method: :put %></li>
            <li><%= link_to "削除する", loan,  method: :delete,
                                        date: { confirm: "本当によろしいですか?"} %></li>
            <% end %>
        <% end %>
    </div>
<script>
    # function coladd() {
    #     var table = document.getElementById("table");
    #     // 行を行末に追加
    #     var row = table.insertRow(-1);
    #     //td分追加
    #     var cell1 = row.insertCell(-1);
    #     var cell2 = row.insertCell(-1);
    #     // セルの内容入力
    #     cell1.innerHTML = '<input>';
    #     cell2.innerHTML = 'この行を削除しますか？<input type="button" value=削除" id="coladd" onclick="coldel(this)">';
    # }
    # function coldel(obj) {
    #     // 削除ボタンを押下された行を取得
    #     tr = obj.parentNode.parentNode;
    #     // trのインデックスを取得して行を削除する
    #     tr.parentNode.deleteRow(tr.sectionRowIndex);
    # }
</script>
    </body>
</html>

app/views/wishes/new.html.erb
<h1>欲しいものを追加する</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
  <%= form_for(@wish) do |f| %>
    <%= f.label :商品名 %>
    <%= f.text_field :name %>

    <%= f.label :金額 %>
    <%= f.number_field :price %>

    <%= f.submit "決定", class: "btn btn-primary" %>
  <% end %>
  </div>
</div>